# Generated by Django 5.2.5 on 2025-08-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='D12UDT', max_length=6, unique=True),
        ),
    ]
